name: Rain Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  run-rain-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Rain Alert
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          SENDERS_EMAIL: ${{ secrets.SENDERS_EMAIL }}
          RECEIVERS_EMAIL: ${{ secrets.RECEIVERS_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
