name: Rain Alert

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  run-rain-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run rain alert
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          SENDERS_EMAIL: ${{ secrets.SENDERS_EMAIL }}
          RECEIVERS_EMAIL: ${{ secrets.RECEIVERS_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
